typography_spectrum: 0.3553191
color:
  brandColors:
    - '#FEFFF5'
    - '#78746B'
    - '#A49B8A'
    - '#DADBCB'
    - '#0C0B0A'
  brandStrength: 0.9375
  lightness: 0.8340425
  saturation: 0.5
  rhythmicContrast: 0.7234042
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Miranda Westerhof
  email: stoel10hairdo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1e214c9d-906e-41a4-a75b-f428c9978447.jpg
name: Stoel10Hairdo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Stoel10Hairdo
description: Wij knippen al je zorgen weg
purpose: []
