typography_spectrum: 0.34292354341596365
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.9117173997219652
  lightness: 0.41328860842622817
  saturation: 0.7667903688270599
  rhythmicContrast: 0.2412597795482725
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Miranda Westerhof
  email: stoel10hairdo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1e214c9d-906e-41a4-a75b-f428c9978447.jpg
name: Stoel10Hairdo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Stoel10Hairdo
description: Wij knippen al je zorgen weg
purpose: []
